### ISSUE TITLE
Add request for the x10minipro mimmi

### ISSUE THREAD

**Issue by dams2011** [koush/ROMManagerManifest#404]
https://github.com/dams2011

**Comment by koush** [comment]
? i dont see a source repo.?

**Comment by dams2011** [comment]
https://github.com/dams2011/android_device_semc_mimmi

**Comment by dams2011** [comment]
Error message when I try to set my manual manifest:
Error processing your manifest: "Unknown token after start:<

https://github.com/dams2011/ROMManagerManifest/blob/gh-pages/mimmiroms.js

or would have to upload mimmiroms.js on a server?

**Comment by koush** [comment]
You need to provide the raw url. Click raw in that page you linked for the raw url

**Comment by dams2011** [comment]
Error processing your manifest: "Unknown token after start:<"

I still get the error

https://raw.github.com/dams2011/ROMManagerManifest/gh-pages/mimmiroms.js

**Comment by dams2011** [comment]
Error processing your manifest: {"stack":"SyntaxError: Unexpected end of input\n at Object.parse (native)\n at Object.parse (/deployfu/slave/developer/master/dirty.js:423:28)\n at Object.parse (/deployfu/slave/developer/master/dirty.js:432:16)\n at IncomingMessage.<anonymous>

**Comment by koush** [comment]
Can you try hosting it on another free site, specifically meant to be for hosting webpages? Not sure why this is not working. The JSON actually looks fine. May be a github issue.

**Comment by koush** [comment]
You can always just host your ROMs directly on the developer portal and not mess with the manifest at all.

**Comment by dams2011** [comment]
ok thank you very much finish the roms and will upload directly into the developer portal :)
